export enum RepositoryToken {
  CARS_REPOSITORY = "CARS_REPOSITORY",
  CATEGORIES_REPOSITORY = "CATEGORIES_REPOSITORY",
  SPECIFICATIONS_REPOSITORY = "SPECIFICATIONS_REPOSITORY",
  USERS_REPOSITORY = "USERS_REPOSITORY",
}
